name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.os.type }})
    strategy:
      matrix:
        os:
          - type: ubuntu-latest
            deps: sudo apt-get install libxi-dev libxinerama-dev libxcursor-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev libxrandr-dev libxxf86vm-dev xvfb libglm-dev
          - type: macos-latest
            deps: brew install glm glew
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup System Dependencies
      run: ${{ matrix.os.deps }}
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
